### ISSUE TITLE
CIFAR-FS & FC100 pretrained model

### ISSUE THREAD

**Issue by TINA-WA** [Han-Jia/UNICORN-MAML#10]
Hi, thanks for sharing code. If we want to see the performance on cifar-fs and fc100,
can we get access to the pretrained weights on CIFAR-FS & FC100 datasets?
![image](https://github.com/Han-Jia/UNICORN-MAML/assets/46915657/2740d869-2f34-46b1-bb40-56af56de2d0d)

Or just simply train without pretrained model??

**Comment by TINA-WA** [comment]
@Han-Jia

**Comment by Han-Jia** [comment]
Hi,

I uploaded the weights to the google drive, please download from this [link](https://drive.google.com/drive/folders/14Jn1t9JxH-CxjfWy4JmVpCxkC9cDqqfE):
