### ISSUE TITLE
Question about zero_grad

### ISSUE THREAD

**Issue by buptxiaofeng** [Han-Jia/UNICORN-MAML#7]
https://github.com/Han-Jia/UNICORN-MAML/blob/c66b9f347f52afb5a988e4c679c9d398a41f9ae3/model/trainer/fsl_trainer.py#L152

Hi, thanks for sharing code. It seems that zero_grad is usually before the backward. Is there any reason to zero_grad after the backward here? Or it really doesn't matter?

**Comment by Han-Jia** [comment]
It does not matter. There is a zero_grad in line 121, so the zero_grad in line 152 works for the next iteration.
