### ISSUE TITLE
在colab中运行

### ISSUE THREAD

**Issue by ERICZIO** [Han-Jia/UNICORN-MAML#9]
报错显示ImportError: cannot import name 'FewShotModel' from 'model.models.base' (/content/UNICORN-MAML/model/models/base.py)，应该怎么解决呢

**Comment by TINA-WA** [comment]
这个在作者的另一个项目中：
![image](https://github.com/Han-Jia/UNICORN-MAML/assets/46915657/5838cb40-c98c-4ec0-8f9e-285b04b7b69a)

https://github.com/Sha-Lab/FEAT/blob/47bdc7c1672e00b027c67469d0291e7502918950/model/models/base.py

**Comment by ERICZIO** [comment]
ERIC have received.Thank you.

**Comment by ERICZIO** [comment]
ERIC have received.Thank you.
